# https://projecteuler.net/problem=2
#
# Even Fibonacci numbers 
# Problem 2 
# Each new term in the Fibonacci sequence is
# generated by adding the previous two terms. By starting with 1 and 2, the
# first 10 terms will be:
#
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#
# By considering the terms in the Fibonacci sequence whose values do not exceed
# four million, find the sum of the even-valued terms.
#



# Generates sum of even fibonacci numbers less than "maxAllowed"
#
def generateFibSum(maxAllowed):
        num1 = 1
        num2 = 2
        total = 0

        while (num2 <= maxAllowed) : 
                print num2
                if (num2 % 2 == 0):
                        total += num2
                temp = num1 + num2
                num1 = num2
                num2 = temp
        
        return total


maxAllowed = 4000000
#maxAllowed = 100
print "for max range of %d, sum of even fibonacci = %d " % \
        (maxAllowed, generateFibSum(maxAllowed))
